import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  header: { backgroundColor: COLORS.navy, paddingHorizontal: 20, paddingTop: 56, paddingBottom: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  greeting: { fontSize: 13, color: COLORS.gray400 },
  name: { fontSize: 20, fontWeight: 'bold', color: COLORS.white, marginTop: 2 },
  avatarCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.gold, justifyContent: 'center', alignItems: 'center' },
  avatarText: { fontSize: 16, fontWeight: 'bold', color: COLORS.white },
  statsBar: { backgroundColor: COLORS.navyLight, flexDirection: 'row', paddingVertical: 16 },
  statItem: { flex: 1, alignItems: 'center' },
  statNum: { fontSize: 20, fontWeight: 'bold', color: COLORS.gold },
  statLabel: { fontSize: 11, color: COLORS.gray400, marginTop: 2 },
  statDivider: { width: 1, backgroundColor: COLORS.gray700, marginVertical: 4 },
  section: { paddingHorizontal: 16, paddingTop: 20 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: 17, fontWeight: 'bold', color: COLORS.navy },
  seeAll: { fontSize: 13, color: COLORS.gold, fontWeight: '600' },
  card: { backgroundColor: COLORS.white, borderRadius: 16, marginRight: 14, width: 200, overflow: 'hidden', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6 },
  cardImage: { width: '100%', height: 130 },
  topBadge: { position: 'absolute', top: 10, left: 10, backgroundColor: COLORS.gold, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  topBadgeText: { fontSize: 10, color: COLORS.white, fontWeight: 'bold' },
  cardBody: { padding: 12 },
  cardName: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy },
  cardType: { fontSize: 11, color: COLORS.gray500, marginTop: 2 },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  cardPrice: { fontSize: 15, color: COLORS.gold, fontWeight: 'bold' },
  perNight: { fontSize: 11, color: COLORS.gray400, fontWeight: 'normal' },
  ratingBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.goldLight, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  ratingText: { fontSize: 11, color: COLORS.goldDark, fontWeight: 'bold' },
  recentCard: { backgroundColor: COLORS.white, borderRadius: 12, padding: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', elevation: 2 },
  recentLeft: { flex: 1, marginRight: 12 },
  recentRoom: { fontSize: 15, fontWeight: 'bold', color: COLORS.navy },
  recentDate: { fontSize: 12, color: COLORS.gray500, marginTop: 3 },
  recentBadge: { backgroundColor: COLORS.greenLight, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  recentBadgeText: { fontSize: 12, color: COLORS.green, fontWeight: 'bold' },
});