import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite, alignItems: 'center', justifyContent: 'center', padding: 24 },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.green + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  title: { fontSize: 26, fontWeight: 'bold', color: COLORS.navy, textAlign: 'center', marginBottom: 8 },
  subtitle: { fontSize: 14, color: COLORS.gray500, textAlign: 'center', marginBottom: 32 },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    marginBottom: 32,
    elevation: 2,
  },
  cardTitle: { fontSize: 13, fontWeight: 'bold', color: COLORS.gray400, letterSpacing: 0.5, marginBottom: 14 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  rowLabel: { fontSize: 14, color: COLORS.gray500 },
  rowValue: { fontSize: 14, fontWeight: '600', color: COLORS.navy },
  divider: { height: 1, backgroundColor: COLORS.gray100, marginVertical: 10 },
  totalLabel: { fontSize: 15, fontWeight: 'bold', color: COLORS.navy },
  totalValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.gold },
  primaryBtn: {
    backgroundColor: COLORS.gold,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  primaryBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  secondaryBtn: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    width: '100%',
    borderWidth: 1.5,
    borderColor: COLORS.gray200,
  },
  secondaryBtnText: { color: COLORS.navy, fontWeight: '600', fontSize: 15 },
});
