import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  header: { backgroundColor: COLORS.navy, padding: 20, paddingTop: 56 },
  title: { fontSize: 24, fontWeight: 'bold', color: COLORS.white },
  subtitle: { fontSize: 13, color: COLORS.gray400, marginTop: 4 },
  list: { padding: 16 },
  card: { backgroundColor: COLORS.white, borderRadius: 16, marginBottom: 14, overflow: 'hidden', elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
  cardImage: { width: '100%', height: 130 },
  cardBody: { padding: 14 },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  roomName: { fontSize: 16, fontWeight: 'bold', color: COLORS.navy, flex: 1, marginRight: 10 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  confirmed: { backgroundColor: COLORS.greenLight },
  pending: { backgroundColor: COLORS.yellowLight },
  cancelled: { backgroundColor: COLORS.redLight },
  confirmedText: { fontSize: 12, color: COLORS.green, fontWeight: 'bold' },
  pendingText: { fontSize: 12, color: COLORS.yellow, fontWeight: 'bold' },
  cancelledText: { fontSize: 12, color: COLORS.red, fontWeight: 'bold' },
  dateRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 12 },
  dateBlock: { flex: 1 },
  dateLabel: { fontSize: 10, fontWeight: '700', color: COLORS.gray400, letterSpacing: 0.5, marginBottom: 3 },
  dateValue: { fontSize: 13, fontWeight: '600', color: COLORS.navy },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: COLORS.gray100, paddingTop: 10 },
  nights: { fontSize: 13, color: COLORS.gray500 },
  price: { fontSize: 18, fontWeight: 'bold', color: COLORS.gold },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40, marginTop: 60 },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.navy, marginBottom: 8 },
  emptyText: { fontSize: 14, color: COLORS.gray500, textAlign: 'center' },
});