import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f6f3',
  },
  header: {
    backgroundColor: COLORS.navy,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight! + 20 : 56,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerDate: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.45)',
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.gold,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 14,
  },
  roleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(212,165,116,0.13)',
    borderColor: 'rgba(212,165,116,0.25)',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 5,
    gap: 4,
  },
  roleBadgeText: {
    color: COLORS.gold,
    fontSize: 12,
    fontWeight: '600',
  },
  headerStatsText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: COLORS.white,
    width: '48%',
    borderRadius: 16,
    padding: 16,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f0ede8',
  },
  statCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  statIconBox: {
    width: 36,
    height: 36,
    borderRadius: 14,
    backgroundColor: 'rgba(212,165,116,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statBadge: {
    backgroundColor: COLORS.greenLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  statBadgeText: {
    color: COLORS.green,
    fontSize: 11,
    fontWeight: 'bold',
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.navy,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.gray400,
  },
  sectionBox: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f0ede8',
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.navy,
  },
  soonBadge: {
    backgroundColor: COLORS.gray200,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 8,
  },
  soonBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: COLORS.gray500,
    textTransform: 'uppercase',
  },
  analyticsToggle: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    padding: 2,
  },
  analyticsTabActive: {
    backgroundColor: COLORS.navy,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  analyticsTabInactive: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  analyticsTabTextActive: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600',
  },
  analyticsTabTextInactive: {
    color: COLORS.gray500,
    fontSize: 12,
    fontWeight: '600',
  },
  chartPlaceholder: {
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafafa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f0ede8',
    borderStyle: 'dashed',
  },
  bookingStatusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  statusBlock: {
    width: '48%',
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusBlockLabel: {
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 2,
  },
  statusBlockValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.navy,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  quickActionCard: {
    backgroundColor: COLORS.white,
    width: '48%',
    borderRadius: 16,
    padding: 16,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f0ede8',
  },
  quickActionEmoji: {
    fontSize: 24,
    marginBottom: 10,
  },
  quickActionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 2,
  },
  quickActionDesc: {
    fontSize: 12,
    color: COLORS.gray400,
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.gold,
  },
  recentBookingCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#f0ede8',
    alignItems: 'center',
    gap: 12,
  },
  recentBookingImage: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: COLORS.gray200,
  },
  recentBookingInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  recentBookingRoom: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.navy,
    marginBottom: 2,
  },
  recentBookingDate: {
    fontSize: 12,
    color: COLORS.gray400,
  },
  recentBookingRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  recentBookingPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
});
