import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  image: { width: '100%', height: 280 },
  backBtn: { position: 'absolute', top: 48, left: 16, backgroundColor: 'rgba(10,30,61,0.6)', borderRadius: 20, padding: 8 },
  body: { padding: 20 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  name: { fontSize: 22, fontWeight: 'bold', color: COLORS.navy, flex: 1 },
  price: { fontSize: 22, color: COLORS.gold, fontWeight: 'bold' },
  perNight: { fontSize: 12, color: COLORS.gray400, textAlign: 'right' },
  type: { fontSize: 14, color: COLORS.gray500, marginTop: 4 },
  rating: { fontSize: 14, color: COLORS.gray600, marginTop: 6 },
  divider: { height: 1, backgroundColor: COLORS.gray200, marginVertical: 16 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.navy, marginBottom: 10 },
  description: { fontSize: 14, color: COLORS.gray600, lineHeight: 22 },
  amenities: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  amenity: { backgroundColor: COLORS.goldLight, paddingHorizontal: 12, paddingVertical: 5, borderRadius: 8 },
  amenityText: { fontSize: 13, color: COLORS.goldDark, fontWeight: '500' },
  dateSection: { marginTop: 4 },
  dateRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  dateBox: { flex: 1, borderWidth: 1.5, borderColor: COLORS.gray200, borderRadius: 10, padding: 12, backgroundColor: COLORS.white },
  dateLabel: { fontSize: 11, color: COLORS.gray400, marginBottom: 4 },
  dateValue: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy },
  datePlaceholder: { fontSize: 14, color: COLORS.gray300 },
  summary: { backgroundColor: COLORS.navy, borderRadius: 12, padding: 16, marginTop: 8 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  summaryLabel: { fontSize: 13, color: COLORS.gray400 },
  summaryValue: { fontSize: 13, color: COLORS.white, fontWeight: '500' },
  summaryTotal: { fontSize: 16, color: COLORS.gold, fontWeight: 'bold' },
  button: { backgroundColor: COLORS.gold, margin: 20, marginTop: 12, padding: 16, borderRadius: 12, alignItems: 'center' },
  buttonDisabled: { backgroundColor: COLORS.gray300 },
  buttonText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  // Reviews section
  reviewSection: { paddingHorizontal: 20, paddingTop: 0 },
  reviewSectionTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.navy, marginBottom: 12 },
  reviewCard: { backgroundColor: COLORS.white, borderRadius: 12, padding: 14, marginBottom: 10, elevation: 1 },
  reviewStars: { flexDirection: 'row', gap: 3, marginBottom: 4 },
  reviewUser: { fontSize: 13, fontWeight: '600', color: COLORS.navy },
  reviewText: { fontSize: 13, color: COLORS.gray600, lineHeight: 20, marginTop: 6 },
  reviewDate: { fontSize: 11, color: COLORS.gray400, marginTop: 4 },
  reviewEmpty: { color: COLORS.gray400, fontSize: 13, textAlign: 'center', paddingVertical: 8 },

  // Gallery dots
  dotsRow: { position: 'absolute', bottom: 12, alignSelf: 'center', flexDirection: 'row', gap: 6 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.5)' },
  dotActive: { backgroundColor: COLORS.white, width: 18 },

  // Guest count selector
  guestRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12, paddingVertical: 12, paddingHorizontal: 14, backgroundColor: COLORS.white, borderRadius: 10, borderWidth: 1.5, borderColor: COLORS.gray200 },
  guestLabel: { fontSize: 14, fontWeight: '600', color: COLORS.navy },
  guestControls: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  guestBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: COLORS.gray100, alignItems: 'center', justifyContent: 'center' },
  guestBtnDisabled: { backgroundColor: COLORS.gray100, opacity: 0.5 },
  guestCount: { fontSize: 18, fontWeight: 'bold', color: COLORS.navy, minWidth: 24, textAlign: 'center' },
});