import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  header: { backgroundColor: COLORS.navy, padding: 20, paddingTop: 56 },
  title: { fontSize: 24, fontWeight: 'bold', color: COLORS.white },
  subtitle: { fontSize: 13, color: COLORS.gray400, marginTop: 2, marginBottom: 14 },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  searchInput: { flex: 1, fontSize: 14, color: COLORS.white, paddingVertical: 0 },
  filterBtn: { backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 8, padding: 4, position: 'relative' },
  filterBadge: { position: 'absolute', top: -2, right: -2, width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.red },
  filters: { marginTop: 16, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.1)', paddingTop: 16 },
  filterLabel: { fontSize: 12, fontWeight: '600', color: COLORS.gray400, letterSpacing: 0.5, marginBottom: 8 },
  filterValue: { color: COLORS.gold, fontWeight: 'bold' },
  typeChip: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6, marginRight: 8 },
  typeChipActive: { backgroundColor: COLORS.gold, borderColor: COLORS.gold },
  typeChipText: { fontSize: 13, color: COLORS.gray400 },
  typeChipTextActive: { color: COLORS.white, fontWeight: 'bold' },
  sliderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  sliderStep: { flex: 1, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.15)' },
  sliderStepActive: { backgroundColor: COLORS.gold },
  sliderLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  sliderLabelText: { fontSize: 11, color: COLORS.gray400 },
  list: { padding: 16 },
  card: { backgroundColor: COLORS.white, borderRadius: 16, marginBottom: 16, overflow: 'hidden', elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
  image: { width: '100%', height: 180 },
  unavailableOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', alignItems: 'center' },
  unavailableText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16, letterSpacing: 2 },
  topBadge: { position: 'absolute', top: 12, left: 12, backgroundColor: COLORS.gold, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  topBadgeText: { fontSize: 11, color: COLORS.white, fontWeight: 'bold' },
  body: { padding: 14 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  name: { fontSize: 16, fontWeight: 'bold', color: COLORS.navy, flex: 1, marginRight: 8 },
  price: { fontSize: 18, color: COLORS.gold, fontWeight: 'bold', textAlign: 'right' },
  perNight: { fontSize: 11, color: COLORS.gray400, textAlign: 'right' },
  type: { fontSize: 13, color: COLORS.gray500, marginTop: 4 },
  amenities: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  amenity: { backgroundColor: COLORS.gray100, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  amenityText: { fontSize: 11, color: COLORS.gray600 },
  footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
  rating: { fontSize: 13, color: COLORS.gray500 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  available: { backgroundColor: COLORS.greenLight },
  unavailable: { backgroundColor: COLORS.redLight },
  availableText: { fontSize: 12, color: COLORS.green, fontWeight: 'bold' },
  unavailableTextBadge: { fontSize: 12, color: COLORS.red, fontWeight: 'bold' },
  empty: { alignItems: 'center', paddingVertical: 60 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyTitle: { fontSize: 17, fontWeight: 'bold', color: COLORS.navy, marginBottom: 6 },
  emptyText: { fontSize: 14, color: COLORS.gray400 },
});