import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.offWhite },
  header: { backgroundColor: COLORS.navy, padding: 20, paddingTop: 56, flexDirection: 'row', alignItems: 'center', gap: 14 },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
  image: { width: '100%', height: 200 },
  body: { padding: 20 },
  statusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  roomTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.navy, flex: 1, marginRight: 12 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 8 },
  confirmed: { backgroundColor: COLORS.greenLight },
  pending: { backgroundColor: COLORS.yellowLight },
  cancelled: { backgroundColor: COLORS.redLight },
  confirmedText: { color: COLORS.green, fontWeight: 'bold', fontSize: 13 },
  pendingText: { color: COLORS.yellow, fontWeight: 'bold', fontSize: 13 },
  cancelledText: { color: COLORS.red, fontWeight: 'bold', fontSize: 13 },
  card: { backgroundColor: COLORS.white, borderRadius: 14, padding: 16, marginBottom: 14, elevation: 2 },
  cardTitle: { fontSize: 13, fontWeight: 'bold', color: COLORS.gray400, letterSpacing: 0.5, marginBottom: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  rowLabel: { fontSize: 14, color: COLORS.gray500 },
  rowValue: { fontSize: 14, fontWeight: '600', color: COLORS.navy },
  divider: { height: 1, backgroundColor: COLORS.gray100, marginVertical: 10 },
  totalLabel: { fontSize: 15, fontWeight: 'bold', color: COLORS.navy },
  totalValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.gold },
  feeNote: { fontSize: 12, color: COLORS.red, marginTop: 4, textAlign: 'right' },
  cancelBtn: { margin: 20, marginTop: 4, backgroundColor: COLORS.white, borderWidth: 1.5, borderColor: COLORS.red, borderRadius: 12, padding: 15, alignItems: 'center' },
  cancelBtnText: { color: COLORS.red, fontWeight: 'bold', fontSize: 15 },
  cancelledNote: { margin: 20, marginTop: 4, backgroundColor: COLORS.redLight, borderRadius: 12, padding: 14, alignItems: 'center' },
  cancelledNoteText: { color: COLORS.red, fontSize: 14, fontWeight: '500' },
  // Completed status
  completed: { backgroundColor: '#dbeafe' },
  completedText: { color: '#2563eb', fontWeight: 'bold', fontSize: 13 },
  // Action buttons
  rescheduleBtn: { margin: 20, marginBottom: 0, marginTop: 4, backgroundColor: COLORS.white, borderWidth: 1.5, borderColor: COLORS.gold, borderRadius: 12, padding: 15, alignItems: 'center' },
  rescheduleBtnText: { color: COLORS.gold, fontWeight: 'bold', fontSize: 15 },
  reviewBtn: { margin: 20, marginTop: 4, backgroundColor: COLORS.gold, borderRadius: 12, padding: 15, alignItems: 'center' },
  reviewBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 15 },
  reviewedNote: { margin: 20, marginTop: 4, backgroundColor: COLORS.greenLight, borderRadius: 12, padding: 14, alignItems: 'center' },
  reviewedNoteText: { color: COLORS.green, fontSize: 14, fontWeight: '500' },
  // Shared modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: COLORS.white, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, paddingBottom: 40 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.navy, marginBottom: 20, textAlign: 'center' },
  modalLabel: { fontSize: 13, color: COLORS.gray500, marginBottom: 6, fontWeight: '600' },
  modalInput: { borderWidth: 1, borderColor: COLORS.gray200, borderRadius: 8, padding: 12, color: COLORS.navy, fontSize: 14, height: 80, textAlignVertical: 'top' },
  modalInputError: { borderColor: COLORS.red },
  modalError: { color: COLORS.red, fontSize: 12, marginTop: 4, marginBottom: 4 },
  starsRow: { flexDirection: 'row', gap: 12, justifyContent: 'center', marginBottom: 4 },
  modalSaveBtn: { backgroundColor: COLORS.gold, borderRadius: 12, padding: 15, alignItems: 'center', marginTop: 16 },
  modalSaveBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 15 },
  modalCancelBtn: { borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 8 },
  modalCancelBtnText: { color: COLORS.gray500, fontSize: 14 },
  dateRow2: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  dateBox2: { flex: 1, borderWidth: 1.5, borderColor: COLORS.gray200, borderRadius: 10, padding: 12, backgroundColor: COLORS.offWhite },
  dateLabel2: { fontSize: 11, color: COLORS.gray400, marginBottom: 4 },
  dateValue2: { fontSize: 14, fontWeight: 'bold', color: COLORS.navy },
  datePlaceholder2: { fontSize: 14, color: COLORS.gray300 },
});